export const STYLE_ID = 'dsh-later-styles';

const COMPONENTS = [
'/* ==================== 输入行容器 ==================== */',
'.ss-sched-row { display: inline-flex; align-items: center; gap: 4px; flex: none; }',
'',
'/* ==================== ⏰ 按钮（输入框右侧工具按钮） ==================== */',
'/* 对齐官方 ui-conversation trigger：28×28、secondary 色、hover interactive-bg-hover */',
'.ss-sched-btn {',
'  display: inline-grid; place-items: center; width: 28px; height: 28px;',
'  border: none; border-radius: 999px; cursor: pointer; padding: 0;',
'  color: var(--dsw-alias-label-secondary); background: transparent;',
'  transition: background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-sched-btn:hover:not(:disabled) {',
'  background: var(--dsw-alias-interactive-bg-hover);',
'}',
'.ss-sched-btn:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px;',
'}',
'.ss-sched-btn:disabled {',
'  cursor: default; color: var(--dsw-alias-label-dimmed); opacity: 0.4;',
'}',
'.ss-sched-btn.ss-active {',
'  background: var(--dsw-alias-interactive-bg-active);',
'}',
'',
'/* ==================== 待发送提醒 dock（像素级对齐 QueueDock；行内保留 boss 进度条） ==================== */',
'/* 外壳几何与 QueueDock .dock 一致（含负下边距贴住 composer 栈）。 */',
'.ss-dock-root {',
'  box-sizing: border-box; flex: none;',
'  width: calc(100% - var(--dsh-composer-side-clearance) - var(--dsh-composer-side-clearance)',
'    - var(--dsh-composer-dock-inset) - var(--dsh-composer-dock-inset));',
'  max-width: calc(var(--dsh-composer-card-max-width) - var(--dsh-composer-dock-inset) - var(--dsh-composer-dock-inset));',
'  margin: 0 auto calc(0px - var(--dsh-composer-stack-gap) - 3px);',
'  padding: 0 var(--dsh-composer-dock-inset);',
'}',
'/* 面板与 QueueDock .panel 一致：bg tip、顶部圆角、::after 画描边（留底边开口）。 */',
'.ss-dock-body {',
'  position: relative; overflow: hidden; width: 100%; padding: 2px 0;',
'  background: var(--dsw-specific-tip);',
'  border-radius: 12px 12px 0 0;',
'  --dsh-scrollbar-thumb: var(--dsw-alias-scrollbar-bg-l2);',
'  --dsh-scrollbar-thumb-hover: var(--dsw-alias-scrollbar-hover-l2);',
'}',
'.ss-dock-body::after {',
"  content: ''; position: absolute; inset: 0; pointer-events: none;",
'  border: 1px solid var(--dsw-alias-border-l1); border-bottom: none; border-radius: inherit;',
'}',
'.ss-dock-header {',
'  box-sizing: border-box; display: flex; align-items: center; gap: 10px;',
'  width: 100%; height: 36px; padding: 4px 12px;',
'  background: none; border: none; border-radius: 8px; cursor: pointer; text-align: left;',
'  color: var(--dsw-alias-label-primary);',
'}',
'.ss-dock-header:focus-visible { outline: 2px solid var(--dsw-alias-label-tertiary); outline-offset: -2px; }',
'.ss-dock-lead { display: grid; place-items: center; color: var(--dsw-alias-label-tertiary); flex: none; }',
'.ss-dock-count {',
'  flex: auto; min-width: 0;',
'  font-family: Inter, var(--dsw-font-family);',
'  font-size: 13px; font-weight: 500; line-height: 24px;',
'}',
'.ss-dock-chevron { display: grid; place-items: center; width: 14px; height: 14px; color: var(--dsw-alias-label-tertiary); flex: none; }',
'.ss-dock-chevron.ss-open { transform: rotate(180deg); }',
'.ss-dock-list {',
'  margin: 0; padding: 0; list-style: none;',
'  max-height: 180px; overflow-y: auto;',
'}',
'.ss-dock-row {',
'  box-sizing: border-box; display: flex; align-items: center; gap: 10px;',
'  width: 100%; min-height: 36px; padding: 4px 5px 4px 12px; border-radius: 8px;',
'}',
'.ss-dock-row + .ss-dock-row { box-shadow: inset 0 1px 0 var(--dsw-alias-border-l1); }',
'/* QueueDock 的 preview 是单行文本；同位放「时间 · 倒计时 · 内容」+ boss 进度条（保留插件特性）。 */',
'.ss-dock-preview {',
'  flex: auto; min-width: 0; display: flex; flex-direction: column; gap: 4px;',
'  font: var(--dsw-font-xs-13); font-family: Inter, var(--dsw-font-family);',
'}',
'.ss-dock-row-line { display: flex; align-items: center; gap: 8px; min-width: 0; }',
'.ss-dock-row-time { flex: none; color: var(--dsw-alias-label-tertiary); font-variant-numeric: tabular-nums; }',
'.ss-dock-row-countdown { flex: none; color: var(--dsw-alias-label-tertiary); font-variant-numeric: tabular-nums; }',
'.ss-dock-row-countdown.ss-due { color: var(--dsw-alias-state-warn-secondary); }',
'.ss-dock-row-prompt {',
'  flex: 1; min-width: 0; color: var(--dsw-alias-label-primary-dimmed);',
'  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
'}',
'/* boss 血条（保留）：单根长管 + 等比分隔线（每段 1h）。 */',
'.ss-dock-bars { display: block; }',
'.ss-dock-bar {',
'  position: relative; height: 6px; border-radius: 999px; overflow: hidden;',
'  background: var(--dsw-alias-line-secondary);',
'  --ss-bar-divider: color-mix(in srgb, var(--dsw-alias-label-primary) 35%, transparent);',
'}',
'.ss-dock-bars-compact .ss-dock-bar { height: 4px; }',
'.ss-dock-bar-fill {',
'  position: relative; z-index: 1;',
'  height: 100%; border-radius: 999px; background: var(--dsw-alias-brand-primary);',
'  transition: width 1s linear;',
'}',
'/* 暂停 hatch：几何对齐 demo（6px 轨道、只改 fill、115° 5px 条纹），',
'   但暗色主题下 alias-line-secondary 几乎贴背景——fill 用更高对比条纹 +',
'   略深底，轨道不动，避免像换了另一套组件。 */',
'.ss-dock-row.ss-paused .ss-dock-bar-fill {',
'  background:',
'    repeating-linear-gradient(',
'      115deg,',
'      var(--dsw-alias-label-secondary, #9aa0a8) 0 5px,',
'      transparent 5px 10px',
'    ),',
'    color-mix(in srgb, var(--dsw-alias-label-tertiary, #6b7280) 55%, var(--dsw-alias-line-secondary, #3a3e46));',
'  opacity: 1;',
'  min-width: 10px;',
'  transition: none;',
'}',
'.ss-dock-row.ss-paused .ss-dock-row-countdown { color: var(--dsw-alias-label-tertiary); }',
'.ss-dock-row.ss-paused .ss-dock-row-time,',
'.ss-dock-row.ss-paused .ss-dock-row-prompt { color: var(--dsw-alias-label-secondary); }',
'.ss-dock-action.ss-paused-active { color: var(--dsw-alias-state-success-primary); }',
'/* 分隔线：absolute 跨整个 bar 画 N-1 条等比竖线，渲染在 fill 之前（fill 用 z-index:1 盖住「已填充段」上的刻度）。 */',
'.ss-dock-bar-divider {',
'  position: absolute; inset: 0; pointer-events: none;',
'  background-repeat: no-repeat;',
'}',
'.ss-dock-actions { display: flex; align-items: center; gap: 10px; flex: none; }',
'.ss-dock-action {',
'  display: grid; place-items: center; width: 28px; height: 28px; padding: 0; flex: none;',
'  border: none; border-radius: 999px; background: none; cursor: pointer;',
'  color: var(--dsw-alias-label-tertiary);',
'}',
'.ss-dock-action:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover); }',
'.ss-dock-action:focus-visible { outline: 2px solid var(--dsw-alias-label-tertiary); outline-offset: -2px; }',
'.ss-dock-action:disabled { cursor: default; opacity: 0.45; }',
'/* 插话完成态：QueueDock 无此态，用成功色做轻提示（叠加 disabled 半透明）。 */',
'.ss-dock-action-steer.ss-done { color: var(--dsw-alias-state-success-primary); }',
'.ss-dock-steer-err {',
'  color: var(--dsw-alias-state-warn-secondary); font-size: 12px; line-height: 16px;',
'}',
'/* 行内编辑（QueueDock .editor 同款输入框）。 */',
'.ss-dock-edit-input {',
'  box-sizing: border-box; flex: auto; min-width: 0; height: 28px; padding: 0 8px;',
'  font: var(--dsw-font-xs-13); font-family: Inter, var(--dsw-font-family);',
'  color: var(--dsw-alias-label-primary); background: var(--dsw-alias-bg-base);',
'  border: 1px solid var(--dsw-alias-border-l2); border-radius: 6px; outline: none;',
'}',
'.ss-dock-edit-input:focus { border-color: var(--dsw-alias-state-business-primary); }',
'.ss-dock-row-save {',
'  flex: none; font-size: 12px; line-height: 20px; padding: 0 8px; border-radius: 6px;',
'  border: 1px solid var(--dsw-alias-brand-primary); color: var(--dsw-alias-brand-primary);',
'  background: transparent; cursor: pointer;',
'}',
'.ss-dock-row-save:disabled { opacity: 0.45; cursor: default; }',
'.ss-dock-edit-err {',
'  flex-basis: 100%; color: var(--dsw-alias-state-error-secondary); font-size: 12px; line-height: 16px;',
'}',
'.ss-dock-editing { flex-wrap: wrap; }',
'',
'/* ==================== 面板 ==================== */',
'/* 对齐官方 popover panel：z-index 100、border-inverted、radius 12、字号 12、secondary 文字 */',
'.ss-backdrop {',
'  position: fixed; inset: 0; z-index: 100; background: transparent;',
'}',
'.ss-panel {',
'  position: fixed; z-index: 101;',
'  width: min(340px, calc(100vw - 24px));',
'  background: var(--dsw-specific-menu);',
'  color: var(--dsw-alias-label-secondary);',
'  border: 1px solid var(--dsw-alias-border-inverted); border-radius: 12px;',
'  box-shadow: var(--dsw-shadow-lv3); padding: 12px; box-sizing: border-box;',
'  font-size: 12px; line-height: 20px; font-family: var(--dsw-font-family);',
'}',
'.ss-panel-header {',
'  display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px;',
'}',
'.ss-panel-title {',
'  font-weight: 500; font-size: 13px;',
'  display: inline-flex; align-items: center; gap: 6px;',
'  color: var(--dsw-alias-label-primary);',
'}',
'.ss-panel-close {',
'  width: 24px; height: 24px; border: none; background: transparent;',
'  cursor: pointer; color: var(--dsw-alias-label-tertiary);',
'  border-radius: 999px; display: grid; place-items: center; padding: 0;',
'}',
'.ss-panel-close:hover {',
'  background: var(--dsw-alias-interactive-bg-hover);',
'  color: var(--dsw-alias-label-secondary);',
'}',
'.ss-panel-close:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px;',
'}',
'',
'/* ==================== 快捷芯片（单视图，无 tab） ==================== */',
'.ss-quick-grid {',
'  display: grid; grid-template-columns: 1fr 1fr; gap: 6px;',
'}',
'.ss-quick-chip {',
'  height: 30px; padding: 0 10px;',
'  border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px;',
'  background: transparent; color: var(--dsw-alias-label-secondary);',
'  cursor: pointer; font-size: 12px; line-height: 1.5; font-family: var(--dsw-font-family);',
'  transition: color var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              border-color var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-quick-chip:hover {',
'  color: var(--dsw-alias-label-primary); border-color: var(--dsw-alias-label-dimmed);',
'}',
'.ss-quick-chip.ss-active {',
'  background: var(--dsw-alias-interactive-bg-active);',
'  color: var(--dsw-alias-brand-primary); border-color: var(--dsw-alias-brand-primary);',
'}',
'.ss-quick-chip:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px;',
'}',
'.ss-custom-row {',
'  display: flex; gap: 6px; margin-top: 8px;',
'}',
'.ss-custom-row .ss-input { flex: 1; min-width: 0; }',
'.ss-tasklist-head { margin-top: 10px; }',
'',
'/* ==================== 表单字段 ==================== */',
'/* 对齐官方 fields.module.css：column 布局、label 在上 13px/500、字段间 border-top 分隔 */',
'.ss-field {',
'  display: flex; flex-direction: column; gap: 6px; padding: 12px 0;',
'}',
'.ss-field + .ss-field { border-top: 1px solid var(--dsw-alias-border-l2); }',
'.ss-input {',
'  height: 34px; padding: 0 12px;',
'  border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px;',
'  background: var(--dsw-alias-bg-layer-3); color: var(--dsw-alias-label-primary);',
'  font-size: 13px; line-height: 1.5; font-family: var(--dsw-font-family);',
'  flex: 1; min-width: 0; width: 100%; box-sizing: border-box;',
'}',
'.ss-input:focus-visible {',
'  border-color: var(--dsw-alias-brand-primary); outline: none;',
'}',
'.ss-input:disabled { color: var(--dsw-alias-label-tertiary); cursor: default; }',
'.ss-input.ss-inputInvalid { border-color: var(--dsw-alias-label-error); }',
'',
'/* ==================== 任务列表 ==================== */',
'.ss-tasks { max-height: 160px; overflow-y: auto; margin-bottom: 8px; }',
'.ss-task {',
'  display: flex; align-items: center; gap: 8px; padding: 5px 6px;',
'  border-radius: 4px; font-size: 12px;',
'  transition: background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-task:hover { background: var(--dsw-alias-interactive-bg-hover); }',
'.ss-dot { width: 6px; height: 6px; border-radius: 999px; flex: none; }',
'.ss-dot.scheduled { background: var(--dsw-alias-brand-primary); }',
'.ss-dot.overdue { background: var(--dsw-alias-state-warn-secondary); }',
'.ss-dot.delivered { background: var(--dsw-alias-state-success-primary); }',
'.ss-dot.cancelled { background: var(--dsw-alias-label-dimmed); }',
'.ss-task-status {',
'  display: inline-block; margin-left: 4px; padding: 0 5px;',
'  border-radius: 999px; font-size: 10px; font-weight: 500;',
'  color: var(--dsw-alias-state-warn-label);',
'  background: var(--dsw-alias-state-warn-tertiary);',
'}',
'.ss-task-main { flex: 1; min-width: 0; }',
'.ss-task-time { color: var(--dsw-alias-label-tertiary); font-size: 11px; }',
'.ss-task-prompt {',
'  color: var(--dsw-alias-label-primary);',
'  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
'}',
'.ss-task.cancelled .ss-task-prompt,',
'.ss-task.cancelled .ss-task-time {',
'  text-decoration: line-through; color: var(--dsw-alias-label-dimmed);',
'}',
'.ss-task-del {',
'  flex: none; width: 20px; height: 20px; border: none; background: transparent;',
'  cursor: pointer; color: var(--dsw-alias-label-tertiary);',
'  border-radius: 999px; display: grid; place-items: center; padding: 0;',
'  opacity: 0;',
'  transition: opacity var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              background var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              color var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-task:hover .ss-task-del { opacity: 1; }',
'.ss-task-del:hover {',
'  background: var(--dsw-alias-interactive-bg-hover-danger);',
'  color: var(--dsw-alias-state-error-secondary);',
'}',
'.ss-task-del:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); opacity: 1; }',
'.ss-empty {',
'  color: var(--dsw-alias-label-tertiary); text-align: center;',
'  padding: 10px 0; font-size: 12px;',
'}',
'',
'/* ==================== 底部操作栏 ==================== */',
'/* 对齐官方按钮规格：radius 8、padding 5px 14px、13px、disabled opacity .4 */',
'.ss-footer { display: flex; gap: 8px; align-items: center; }',
'.ss-confirm {',
'  flex: 1; appearance: none; border: 1px solid transparent; border-radius: 8px;',
'  padding: 5px 14px; cursor: pointer;',
'  background: var(--dsw-alias-label-primary); color: var(--dsw-alias-bg-layer-3);',
'  font-size: 13px; line-height: 1.5; font-weight: 500;',
'  transition: background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'  font-family: var(--dsw-font-family);',
'}',
'.ss-confirm:hover:not(:disabled) { background: var(--dsw-alias-button-primary-hover); }',
'.ss-confirm:disabled { opacity: 0.4; cursor: default; }',
'.ss-confirm:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px;',
'}',
'.ss-clear {',
'  flex: none; appearance: none; border: 1px solid var(--dsw-alias-border-l2);',
'  border-radius: 8px; padding: 5px 14px; background: none;',
'  color: var(--dsw-alias-label-secondary); cursor: pointer;',
'  font-size: 13px; line-height: 1.5; font-family: var(--dsw-font-family);',
'}',
'.ss-clear:hover:not(:disabled) {',
'  color: var(--dsw-alias-label-primary); border-color: var(--dsw-alias-label-dimmed);',
'}',
'.ss-clear:disabled { opacity: 0.4; cursor: default; }',
'.ss-clear:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px;',
'}',
'',
'/* ==================== 错误提示 ==================== */',
'/* 对齐官方：纯文字色、无背景色块；hint 12px */',
'.ss-error {',
'  color: var(--dsw-alias-state-error-primary); font-size: 12px;',
'  line-height: 1.5; margin: 0;',
'}',
'.ss-hint { color: var(--dsw-alias-label-tertiary); font-size: 12px; line-height: 1.5; margin: 0; }',
'',
'/* ==================== 侧栏会话行「定时状态」badge（docs/ui/09 路线 B） ==================== */',
'/* 紫为定时专属（浅深通用，对白/深底对比均 ≥3:1）；urgent/overdue 复用宿主 warn/error 别名。 */',
'.ss-presence { display: inline-flex; flex: none; color: #8b5cf6; }',
'.ss-presence-beside { margin-left: 4px; }',
'.ss-presence rect { fill: currentColor; }',
'.ss-presence .ss-presence-ring { opacity: 0.8; animation: ss-presence-breathe 2.4s var(--ds-ease-in-out, ease-in-out) infinite; }',
'.ss-presence .ss-presence-hand { opacity: 1; }',
'.ss-presence[data-state="urgent"] { color: var(--dsw-alias-state-warn-secondary); }',
'.ss-presence[data-state="urgent"] .ss-presence-ring { animation-name: ss-presence-pulse; animation-duration: 0.9s; }',
'.ss-presence[data-state="overdue"] { color: var(--dsw-alias-state-error-primary); }',
'.ss-presence[data-state="overdue"] .ss-presence-ring { animation: none; }',
'@keyframes ss-presence-breathe { 0%, 100% { opacity: 0.65; } 50% { opacity: 1; } }',
'@keyframes ss-presence-pulse { 0%, 100% { opacity: 0.5; } 50% { opacity: 1; } }',
'@media (prefers-reduced-motion: reduce) { .ss-presence .ss-presence-ring { animation: none; } }',
'',
'/* ==================== 悬浮卡片状态行增补（issue #4） ==================== */',
'/* 与宿主 .hoverStatus 行严格同构。宿主 StateDot 实测结构（dsh-client-ui-primitives',
'   的 ._dot_* 运行时样式，10×10 relative + ::before 10px/inset:0 + ::after 6px/inset:2px，',
'   两层同色 → 视觉直径约 8px）：本插件按下述同样的双层写法自绘，避免复用其构建期 hash',
'   类名（_dot_xxxxxx_n 不稳定，宿主升级会静默失效）。',
'   颜色跟随宿主语义色板，不引入插件专属色——文案已说明是定时提醒，点不必再承担',
'   「区分来源」的职责；混入第五种颜色反而与宿主 warning 语义撞车。',
'',
'   ⚠️ 已知限制（浅色适配尚未处理）：以下色值是在**当前深色主题**下从宿主',
'   实测得到的运行时值，宿主自身引用 --dsw-alias-* token，会随主题变化，',
'   而此处是硬编码常量。因此当前仅在深色主题下与宿主一致；切换到浅色主题/',
'   其他配色方案时，本行不会跟随，可能与该卡片其余内容不同步。',
'   修法：实测浅色主题下该卡片的实际底色后，改用对应 token（待办）。 */',
'.ss-hover-status {',
'  display: flex; align-items: center; gap: 8px;',
'  color: #adb2b8; font-size: 12px; line-height: 20px;',
'}',
'/* 状态点：宿主同款双层结构。关键——::before 是 10% 透明度的**光晕**，',
'   不是实心外环；::after 才是 6px 实心核心。若 ::before 不设 opacity，',
'   它会盖住核心并渲染成 10px 实心圆（比宿主明显偏大偏实）。 */',
'.ss-hover-status-dot {',
'  position: relative; display: block; flex: none;',
'  width: 10px; height: 10px;',
'  color: #adb2b8;',
'}',
'.ss-hover-status-dot::before,',
'.ss-hover-status-dot::after {',
'  content: ""; position: absolute; border-radius: 50%; background: currentColor;',
'}',
'.ss-hover-status-dot::before { inset: 0; opacity: 0.1; }',
'.ss-hover-status-dot::after { inset: 2px; }',
'/* 语义映射（对齐宿主 done/ongoing/warning/error 四态色值）：',
'   scheduled → ongoing 灰（中性：已排期，无紧迫性）',
'   urgent    → warning 琥珀（≤5min 即将触发）',
'   overdue   → error 红（已到期，等待会话空闲发送） */',
'.ss-hover-status[data-state="urgent"] .ss-hover-status-dot { color: #f59e0b; }',
'.ss-hover-status[data-state="overdue"] .ss-hover-status-dot { color: #f25a5a; }',
'',
'/* ==================== 设置页（定时提醒卡片） ==================== */',
'/* 视觉对齐官方 PluginCard（dsh-client-ui-settings-plugins 私有组件，同构自实现，',
'   参考 dsh-wakatime 同款做法）：<li> 外框、header 整卡按钮、chevron、折叠 body、',
'   footer 放弃/保存。类名统一 ss-card- 前缀，避免与面板（ss-footer/ss-field-*）冲突。 */',
'.ss-card {',
'  border: 1px solid var(--dsw-alias-border-l2);',
'  background: var(--dsw-alias-bg-layer-3);',
'  border-radius: 12px; list-style: none;',
'  transition: border-color .16s, background .16s;',
'}',
'.ss-card:hover { border-color: var(--dsw-alias-label-dimmed); }',
'.ss-cardOpen { background: var(--dsw-alias-bg-layer-2); border-color: var(--dsw-alias-label-dimmed); }',
'.ss-card-header {',
'  appearance: none; width: 100%; font: inherit; color: inherit; text-align: left;',
'  cursor: pointer; background: none; border: 0; border-radius: 12px;',
'  align-items: center; gap: 12px; padding: 14px 16px; display: flex;',
'}',
'.ss-card-header:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px; }',
'.ss-card-headText { flex-direction: column; flex: 1; gap: 4px; min-width: 0; display: flex; }',
'.ss-card-name { color: var(--dsw-alias-label-primary); font-size: 15px; font-weight: 600; line-height: 1.4; }',
'.ss-card-description { color: var(--dsw-alias-label-tertiary); font-size: 13px; line-height: 1.5; }',
'.ss-card-chevron { color: var(--dsw-alias-label-tertiary); flex: none; transition: transform .16s; }',
'.ss-card-chevronOpen { transform: rotate(180deg); }',
'.ss-card-body { border-top: 1px solid var(--dsw-alias-border-l2); margin: 0 16px; padding-bottom: 8px; }',
'.ss-card-readOnly { color: var(--dsw-alias-label-tertiary); margin: 12px 0 0; font-size: 12px; line-height: 1.5; }',
'.ss-card-pending {',
'  white-space: nowrap; background: var(--dsw-alias-bg-module-platform);',
'  color: var(--dsw-alias-label-secondary); border-radius: 999px; flex: none;',
'  padding: 1px 8px; font-size: 11px; font-weight: 500; line-height: 17px;',
'}',
'.ss-card-fieldHead { align-items: center; gap: 8px; display: flex; }',
'.ss-card-label {',
'  min-width: 0; color: var(--dsw-alias-label-primary); flex: 1;',
'  font-size: 13px; font-weight: 500; line-height: 1.5;',
'}',
'.ss-card-badges { align-items: center; gap: 8px; display: inline-flex; }',
'.ss-card-badge {',
'  white-space: nowrap; background: var(--dsw-alias-bg-module-platform);',
'  color: var(--dsw-alias-label-secondary); border-radius: 999px;',
'  padding: 1px 8px; font-size: 11px; font-weight: 500; line-height: 17px;',
'}',
'.ss-card-reset {',
'  font: inherit; color: var(--dsw-alias-label-secondary); cursor: pointer;',
'  background: none; border: none; padding: 0; font-size: 12px; line-height: 1.5;',
'}',
'.ss-card-reset:hover:not(:disabled) { color: var(--dsw-alias-label-primary); }',
'.ss-card-reset:disabled { cursor: default; }',
'.ss-card-invalid { color: var(--dsw-alias-label-error); margin: 0; font-size: 12px; line-height: 1.5; }',
'.ss-card-footer {',
'  border-top: 1px solid var(--dsw-alias-border-l2);',
'  justify-content: flex-end; align-items: center; gap: 8px;',
'  padding: 12px 0 4px; display: flex;',
'}',
'.ss-card-failed {',
'  min-width: 0; color: var(--dsw-alias-label-error); flex: 1; margin: 0;',
'  font-size: 12px; line-height: 1.5;',
'}',
'.ss-card-discard, .ss-card-save {',
'  appearance: none; font: inherit; cursor: pointer;',
'  border: 1px solid transparent; border-radius: 8px;',
'  padding: 5px 14px; font-size: 13px; line-height: 1.5;',
'}',
'.ss-card-discard { border-color: var(--dsw-alias-border-l2); color: var(--dsw-alias-label-secondary); background: none; }',
'.ss-card-discard:hover:not(:disabled) { color: var(--dsw-alias-label-primary); border-color: var(--dsw-alias-label-dimmed); }',
'.ss-card-save { background: var(--dsw-alias-label-primary); color: var(--dsw-alias-bg-layer-3); }',
'.ss-card-save:hover:not(:disabled) { background: var(--dsw-alias-button-primary-hover); }',
'.ss-card-discard:disabled, .ss-card-save:disabled { opacity: 0.4; cursor: default; }',
'.ss-card-discard:focus-visible, .ss-card-save:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px;',
'}',
].join('\n');

export function injectStyles(): () => void {
  if (typeof document === 'undefined') return () => undefined;
  if (document.querySelector(`style[data-plugin-css="${STYLE_ID}"]`) !== null) {
    return () => undefined;
  }
  const tag = document.createElement('style');
  tag.dataset.plugin = 'dsh-later';
  tag.dataset.pluginCss = STYLE_ID;
  tag.textContent = COMPONENTS;
  document.head.appendChild(tag);
  return () => {
    tag.remove();
  };
}
