export const STYLE_ID = 'dsh-session-scheduler-styles';

const COMPONENTS = [
'/* ==================== 输入行容器 ==================== */',
'.ss-sched-row { display: inline-flex; align-items: center; gap: 4px; flex: none; }',
'',
'/* ==================== ⏰ 按钮（输入框右侧工具按钮） ==================== */',
'/* 对齐官方 ui-conversation trigger：28×28、secondary 色、hover interactive-bg-hover */',
'.ss-sched-btn {',
'  display: inline-grid; place-items: center; width: 28px; height: 28px;',
'  border: none; border-radius: 999px; cursor: pointer; padding: 0;',
'  color: var(--dsw-alias-label-secondary); background: transparent;',
'  transition: background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-sched-btn:hover:not(:disabled) {',
'  background: var(--dsw-alias-interactive-bg-hover);',
'}',
'.ss-sched-btn:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px;',
'}',
'.ss-sched-btn:disabled {',
'  cursor: default; color: var(--dsw-alias-label-dimmed); opacity: 0.4;',
'}',
'.ss-sched-btn.ss-active {',
'  background: var(--dsw-alias-interactive-bg-active);',
'}',
'',
'/* ==================== 待发送提醒 dock（对齐 QueueDock） ==================== */',
'.ss-dock-root {',
'  box-sizing: border-box; flex: none; margin: 0 auto; overflow: hidden;',
'  width: calc(100% - var(--dsh-composer-side-clearance) - var(--dsh-composer-side-clearance)',
'    - var(--dsh-composer-dock-inset) - var(--dsh-composer-dock-inset)',
'    - var(--dsh-composer-dock-inset) - var(--dsh-composer-dock-inset));',
'  max-width: calc(var(--dsh-composer-card-max-width) - var(--dsh-composer-dock-inset) - var(--dsh-composer-dock-inset));',
'  border: 1px solid var(--dsw-alias-border-l1);',
'  background: var(--dsw-specific-tip);',
'  border-radius: 12px;',
'}',
'.ss-dock-body {',
'  display: flex; flex-direction: column; gap: 8px; padding: 6px 12px;',
'}',
'.ss-dock-header {',
'  display: flex; align-items: center; gap: 10px; width: 100%; padding: 0;',
'  background: none; border: none; cursor: pointer; text-align: left;',
'  font-family: var(--dsw-font-family);',
'}',
'.ss-dock-header:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px; }',
'.ss-dock-lead { display: grid; place-items: center; color: var(--dsw-alias-label-tertiary); flex: none; }',
'.ss-dock-title {',
'  color: var(--dsw-alias-label-primary); flex: none;',
'  font-size: 13px; font-weight: 500; line-height: 24px;',
'}',
'.ss-dock-progress {',
'  flex: auto; min-width: 0; color: var(--dsw-alias-label-tertiary);',
'  font-size: 13px; font-weight: 400; line-height: 20px;',
'  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
'}',
'.ss-dock-chevron {',
'  display: grid; place-items: center; color: var(--dsw-alias-label-tertiary); flex: none;',
'  transition: transform var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-dock-chevron.ss-open { transform: rotate(180deg); }',
'.ss-dock-list {',
'  display: flex; flex-direction: column; gap: 8px;',
'  max-height: 180px; overflow-y: auto; margin: 0; padding: 0; list-style: none;',
'}',
'.ss-dock-row { display: flex; align-items: center; gap: 8px; padding: 2px 0; }',
'.ss-dock-row-body { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 3px; }',
'.ss-dock-row-line { display: flex; align-items: center; gap: 8px; min-width: 0; }',
'.ss-dock-row-countdown {',
'  flex: none; color: var(--dsw-alias-label-tertiary); font-size: 12px; line-height: 20px;',
'  font-variant-numeric: tabular-nums;',
'}',
'.ss-dock-row-countdown.ss-due { color: var(--dsw-alias-state-warning-secondary); }',
'.ss-dock-bars { display: flex; flex-direction: column; gap: 2px; }',
'.ss-dock-bars-compact { gap: 1px; }',
'.ss-dock-bars-compact .ss-dock-bar { height: 2px; }',
'.ss-dock-bar {',
'  position: relative; height: 3px; border-radius: 999px; overflow: hidden;',
'  background: var(--dsw-alias-line-secondary);',
'}',
'.ss-dock-bar-fill {',
'  height: 100%; border-radius: 999px; background: var(--dsw-alias-brand-primary);',
'  transition: width 1s linear;',
'}',
'.ss-dock-row-time {',
'  flex: none; color: var(--dsw-alias-label-tertiary); font-size: 12px; line-height: 20px;',
'  font-variant-numeric: tabular-nums;',
'}',
'.ss-dock-row-prompt {',
'  flex: 1; min-width: 0; color: var(--dsw-alias-label-primary); font-size: 13px; line-height: 20px;',
'  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
'}',
'.ss-dock-row-cancel {',
'  flex: none; width: 20px; height: 20px; border: none; background: transparent;',
'  cursor: pointer; color: var(--dsw-alias-label-tertiary); border-radius: 999px;',
'  display: grid; place-items: center; padding: 0; opacity: 0.7;',
'  transition: opacity var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              background var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              color var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-dock-row-cancel:hover {',
'  opacity: 1; background: var(--dsw-alias-interactive-bg-hover-danger);',
'  color: var(--dsw-alias-state-error-secondary);',
'}',
'.ss-dock-row-cancel:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); opacity: 1; }',
'.ss-dock-row-edit {',
'  flex: none; width: 20px; height: 20px; border: none; background: transparent;',
'  cursor: pointer; color: var(--dsw-alias-label-tertiary); border-radius: 999px;',
'  display: grid; place-items: center; padding: 0; opacity: 0.7; font-size: 13px;',
'  transition: opacity var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-dock-row-edit:hover { opacity: 1; background: var(--dsw-alias-interactive-bg-hover); }',
'.ss-dock-row-edit:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); opacity: 1; }',
'.ss-dock-edit-input {',
'  flex: 1; min-width: 0; font: inherit; font-size: 13px; line-height: 20px;',
'  color: var(--dsw-alias-label-primary); background: var(--dsw-alias-interactive-bg-subtle);',
'  border: 1px solid var(--dsw-alias-line-primary); border-radius: 6px; padding: 1px 6px;',
'}',
'.ss-dock-edit-input:focus { outline: 2px solid var(--dsw-alias-brand-primary); border-color: transparent; }',
'.ss-dock-row-save {',
'  flex: none; font-size: 12px; line-height: 20px; padding: 0 8px; border-radius: 6px;',
'  border: 1px solid var(--dsw-alias-brand-primary); color: var(--dsw-alias-brand-primary);',
'  background: transparent; cursor: pointer;',
'}',
'.ss-dock-row-save:disabled { opacity: 0.5; cursor: not-allowed; }',
'.ss-dock-edit-err {',
'  flex-basis: 100%; color: var(--dsw-alias-state-error-secondary); font-size: 12px; line-height: 16px;',
'}',
'.ss-dock-editing { flex-wrap: wrap; }',
'.ss-toast-host {',
'  position: fixed; right: 16px; bottom: 96px; z-index: 300;',
'  display: flex; flex-direction: column; gap: 8px; pointer-events: none;',
'}',
'.ss-toast {',
'  pointer-events: auto; max-width: min(360px, calc(100vw - 32px));',
'  display: flex; align-items: center; gap: 8px;',
'  padding: 9px 12px; border-radius: 10px;',
'  background: var(--dsw-specific-menu); color: var(--dsw-alias-label-primary);',
'  border: 1px solid var(--dsw-alias-line-primary);',
'  box-shadow: 0 6px 20px rgba(0, 0, 0, 0.18);',
'  font-size: 13px; line-height: 18px;',
'  animation: ss-toast-in 180ms var(--ds-ease-out);',
'}',
'.ss-toast-icon { color: var(--dsw-alias-brand-primary); flex: none; }',
'.ss-toast-text { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'@keyframes ss-toast-in { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: none; } }',
'',
'/* ==================== 面板 ==================== */',
'/* 对齐官方 popover panel：z-index 100、border-inverted、radius 12、字号 12、secondary 文字 */',
'.ss-backdrop {',
'  position: fixed; inset: 0; z-index: 100; background: transparent;',
'}',
'.ss-panel {',
'  position: fixed; z-index: 101;',
'  width: min(340px, calc(100vw - 24px));',
'  background: var(--dsw-specific-menu);',
'  color: var(--dsw-alias-label-secondary);',
'  border: 1px solid var(--dsw-alias-border-inverted); border-radius: 12px;',
'  box-shadow: var(--dsw-shadow-lv3); padding: 12px; box-sizing: border-box;',
'  font-size: 12px; line-height: 20px; font-family: var(--dsw-font-family);',
'}',
'.ss-panel-header {',
'  display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px;',
'}',
'.ss-panel-title {',
'  font-weight: 500; font-size: 13px;',
'  display: inline-flex; align-items: center; gap: 6px;',
'  color: var(--dsw-alias-label-primary);',
'}',
'.ss-panel-close {',
'  width: 24px; height: 24px; border: none; background: transparent;',
'  cursor: pointer; color: var(--dsw-alias-label-tertiary);',
'  border-radius: 999px; display: grid; place-items: center; padding: 0;',
'}',
'.ss-panel-close:hover {',
'  background: var(--dsw-alias-interactive-bg-hover);',
'  color: var(--dsw-alias-label-secondary);',
'}',
'.ss-panel-close:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px;',
'}',
'',
'/* ==================== 快捷芯片（单视图，无 tab） ==================== */',
'.ss-quick-grid {',
'  display: grid; grid-template-columns: 1fr 1fr; gap: 6px;',
'}',
'.ss-quick-chip {',
'  height: 30px; padding: 0 10px;',
'  border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px;',
'  background: transparent; color: var(--dsw-alias-label-secondary);',
'  cursor: pointer; font-size: 12px; line-height: 1.5; font-family: var(--dsw-font-family);',
'  transition: color var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              border-color var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-quick-chip:hover {',
'  color: var(--dsw-alias-label-primary); border-color: var(--dsw-alias-label-dimmed);',
'}',
'.ss-quick-chip.ss-active {',
'  background: var(--dsw-alias-interactive-bg-active);',
'  color: var(--dsw-alias-brand-primary); border-color: var(--dsw-alias-brand-primary);',
'}',
'.ss-quick-chip:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px;',
'}',
'.ss-custom-row {',
'  display: flex; gap: 6px; margin-top: 8px;',
'}',
'.ss-custom-row .ss-input { flex: 1; min-width: 0; }',
'.ss-tasklist-head { margin-top: 10px; }',
'',
'/* ==================== 表单字段 ==================== */',
'/* 对齐官方 fields.module.css：column 布局、label 在上 13px/500、字段间 border-top 分隔 */',
'.ss-field {',
'  display: flex; flex-direction: column; gap: 6px; padding: 10px 0;',
'}',
'.ss-field + .ss-field { border-top: 1px solid var(--dsw-alias-border-l2); }',
'.ss-field-head {',
'  display: flex; align-items: center; gap: 8px;',
'}',
'.ss-field-head-right {',
'  display: inline-flex; align-items: center; gap: 8px; flex: none;',
'}',
'.ss-field-label {',
'  flex: 1; min-width: 0; color: var(--dsw-alias-label-primary);',
'  font-size: 13px; font-weight: 500; line-height: 1.5;',
'}',
'.ss-badge {',
'  white-space: nowrap; background: var(--dsw-alias-bg-module-platform);',
'  color: var(--dsw-alias-label-secondary); border-radius: 999px;',
'  padding: 1px 8px; font-size: 11px; font-weight: 500; line-height: 17px;',
'}',
'.ss-reset {',
'  font: inherit; color: var(--dsw-alias-label-secondary); cursor: pointer;',
'  background: none; border: none; padding: 0; font-size: 12px; line-height: 1.5;',
'}',
'.ss-reset:hover:not(:disabled) { color: var(--dsw-alias-label-primary); }',
'.ss-reset:disabled { cursor: default; }',
'.ss-input {',
'  height: 34px; padding: 0 12px;',
'  border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px;',
'  background: var(--dsw-alias-bg-layer-3); color: var(--dsw-alias-label-primary);',
'  font-size: 13px; line-height: 1.5; font-family: var(--dsw-font-family);',
'  flex: 1; min-width: 0; width: 100%; box-sizing: border-box;',
'}',
'.ss-input:focus-visible {',
'  border-color: var(--dsw-alias-brand-primary); outline: none;',
'}',
'.ss-input:disabled { color: var(--dsw-alias-label-tertiary); cursor: default; }',
'.ss-input.ss-invalid { border-color: var(--dsw-alias-state-error-primary); }',
'',
'/* ==================== 任务列表 ==================== */',
'.ss-tasks { max-height: 160px; overflow-y: auto; margin-bottom: 8px; }',
'.ss-task {',
'  display: flex; align-items: center; gap: 8px; padding: 5px 6px;',
'  border-radius: 4px; font-size: 12px;',
'  transition: background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-task:hover { background: var(--dsw-alias-interactive-bg-hover); }',
'.ss-dot { width: 6px; height: 6px; border-radius: 999px; flex: none; }',
'.ss-dot.scheduled { background: var(--dsw-alias-brand-primary); }',
'.ss-dot.overdue { background: var(--dsw-alias-state-warn-secondary); }',
'.ss-dot.delivered { background: var(--dsw-alias-state-success-primary); }',
'.ss-dot.cancelled { background: var(--dsw-alias-label-dimmed); }',
'.ss-task-status {',
'  display: inline-block; margin-left: 4px; padding: 0 5px;',
'  border-radius: 999px; font-size: 10px; font-weight: 500;',
'  color: var(--dsw-alias-state-warn-label);',
'  background: var(--dsw-alias-state-warn-tertiary);',
'}',
'.ss-task-main { flex: 1; min-width: 0; }',
'.ss-task-time { color: var(--dsw-alias-label-tertiary); font-size: 11px; }',
'.ss-task-prompt {',
'  color: var(--dsw-alias-label-primary);',
'  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
'}',
'.ss-task.cancelled .ss-task-prompt,',
'.ss-task.cancelled .ss-task-time {',
'  text-decoration: line-through; color: var(--dsw-alias-label-dimmed);',
'}',
'.ss-task-del {',
'  flex: none; width: 20px; height: 20px; border: none; background: transparent;',
'  cursor: pointer; color: var(--dsw-alias-label-tertiary);',
'  border-radius: 999px; display: grid; place-items: center; padding: 0;',
'  opacity: 0;',
'  transition: opacity var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              background var(--ds-transition-duration-fast) var(--ds-ease-in-out),',
'              color var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'}',
'.ss-task:hover .ss-task-del { opacity: 1; }',
'.ss-task-del:hover {',
'  background: var(--dsw-alias-interactive-bg-hover-danger);',
'  color: var(--dsw-alias-state-error-secondary);',
'}',
'.ss-task-del:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); opacity: 1; }',
'.ss-empty {',
'  color: var(--dsw-alias-label-tertiary); text-align: center;',
'  padding: 10px 0; font-size: 12px;',
'}',
'',
'/* ==================== 底部操作栏 ==================== */',
'/* 对齐官方按钮规格：radius 8、padding 5px 14px、13px、disabled opacity .4 */',
'.ss-footer { display: flex; gap: 8px; align-items: center; }',
'.ss-confirm {',
'  flex: 1; appearance: none; border: 1px solid transparent; border-radius: 8px;',
'  padding: 5px 14px; cursor: pointer;',
'  background: var(--dsw-alias-label-primary); color: var(--dsw-alias-bg-layer-3);',
'  font-size: 13px; line-height: 1.5; font-weight: 500;',
'  transition: background var(--ds-transition-duration-fast) var(--ds-ease-in-out);',
'  font-family: var(--dsw-font-family);',
'}',
'.ss-confirm:hover:not(:disabled) { background: var(--dsw-alias-button-primary-hover); }',
'.ss-confirm:disabled { opacity: 0.4; cursor: default; }',
'.ss-confirm:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px;',
'}',
'.ss-clear {',
'  flex: none; appearance: none; border: 1px solid var(--dsw-alias-border-l2);',
'  border-radius: 8px; padding: 5px 14px; background: none;',
'  color: var(--dsw-alias-label-secondary); cursor: pointer;',
'  font-size: 13px; line-height: 1.5; font-family: var(--dsw-font-family);',
'}',
'.ss-clear:hover:not(:disabled) {',
'  color: var(--dsw-alias-label-primary); border-color: var(--dsw-alias-label-dimmed);',
'}',
'.ss-clear:disabled { opacity: 0.4; cursor: default; }',
'.ss-clear:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px;',
'}',
'',
'/* ==================== 错误提示 ==================== */',
'/* 对齐官方：纯文字色、无背景色块；hint 12px */',
'.ss-error {',
'  color: var(--dsw-alias-state-error-primary); font-size: 12px;',
'  line-height: 1.5; margin: 0;',
'}',
'.ss-hint { color: var(--dsw-alias-label-tertiary); font-size: 12px; line-height: 1.5; margin: 0; }',
'',
'/* ==================== 设置页 ==================== */',
'/* 对齐官方 PluginCard footer：save 实底 label-primary、discard 描边、radius 8、13px */',
'.ss-settings-actions {',
'  display: flex; justify-content: flex-end; align-items: center; gap: 8px;',
'  border-top: 1px solid var(--dsw-alias-border-l2); padding: 12px 0 4px;',
'}',
'.ss-settings-save, .ss-settings-discard {',
'  appearance: none; font: inherit; cursor: pointer;',
'  border: 1px solid transparent; border-radius: 8px;',
'  padding: 5px 14px; font-size: 13px; line-height: 1.5;',
'  font-family: var(--dsw-font-family);',
'}',
'.ss-settings-save {',
'  background: var(--dsw-alias-label-primary); color: var(--dsw-alias-bg-layer-3);',
'}',
'.ss-settings-save:hover:not(:disabled) { background: var(--dsw-alias-button-primary-hover); }',
'.ss-settings-discard {',
'  border-color: var(--dsw-alias-border-l2); color: var(--dsw-alias-label-secondary); background: none;',
'}',
'.ss-settings-discard:hover:not(:disabled) {',
'  color: var(--dsw-alias-label-primary); border-color: var(--dsw-alias-label-dimmed);',
'}',
'.ss-settings-save:disabled, .ss-settings-discard:disabled { opacity: 0.4; cursor: default; }',
'.ss-settings-save:focus-visible, .ss-settings-discard:focus-visible {',
'  outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px;',
'}',
'.ss-settings-error {',
'  color: var(--dsw-alias-state-error-primary); font-size: 12px;',
'  line-height: 1.5; min-width: 0; flex: 1; margin: 0;',
'}',
].join('\n');

export function injectStyles(): () => void {
  if (typeof document === 'undefined') return () => undefined;
  if (document.querySelector(`style[data-plugin-css="${STYLE_ID}"]`) !== null) {
    return () => undefined;
  }
  const tag = document.createElement('style');
  tag.dataset.plugin = 'dsh-session-scheduler';
  tag.dataset.pluginCss = STYLE_ID;
  tag.textContent = COMPONENTS;
  document.head.appendChild(tag);
  return () => {
    tag.remove();
  };
}
